# [EventModule]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [EventModule]    Script Date: 25-04-2024 18:39:18 ******/
CREATE DATABASE [EventModule]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EventModule', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EventModule.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EventModule_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\EventModule_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [EventModule] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EventModule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [EventModule] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [EventModule] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [EventModule] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [EventModule] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [EventModule] SET ARITHABORT OFF 
GO
ALTER DATABASE [EventModule] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [EventModule] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [EventModule] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [EventModule] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [EventModule] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [EventModule] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [EventModule] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [EventModule] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [EventModule] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [EventModule] SET  ENABLE_BROKER 
GO
ALTER DATABASE [EventModule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [EventModule] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [EventModule] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [EventModule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [EventModule] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [EventModule] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [EventModule] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [EventModule] SET RECOVERY FULL 
GO
ALTER DATABASE [EventModule] SET  MULTI_USER 
GO
ALTER DATABASE [EventModule] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [EventModule] SET DB_CHAINING OFF 
GO
ALTER DATABASE [EventModule] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [EventModule] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [EventModule] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [EventModule] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'EventModule', N'ON'
GO
ALTER DATABASE [EventModule] SET QUERY_STORE = ON
GO
ALTER DATABASE [EventModule] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[ActivityTbl]

In [0]:
USE [EventModule]
GO

In [0]:
/****** Object:  Table [dbo].[ActivityTbl]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ActivityTbl](
	[ActivityId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Price] [bigint] NULL,
	[EventId] [bigint] NOT NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[CreatedDateTime] [datetime] NOT NULL,
	[UpdatedDateTime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[ActivityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[AdminTbl]

In [0]:
/****** Object:  Table [dbo].[AdminTbl]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AdminTbl](
	[AdminTblId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](320) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[Mobile] [varchar](10) NOT NULL,
	[Address] [varchar](100) NOT NULL,
	[UpdatedTime] [datetime] NULL,
	[CreatedDatetime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminTblId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[EventTbl]

In [0]:
/****** Object:  Table [dbo].[EventTbl]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EventTbl](
	[EventId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[StartDate] [datetime] NOT NULL,
	[EndDate] [datetime] NOT NULL,
	[Description] [varchar](max) NOT NULL,
	[Image] [varchar](max) NOT NULL,
	[IsActive] [bigint] NOT NULL,
	[IsPublish] [bigint] NOT NULL,
	[CreadDateTime] [datetime] NOT NULL,
	[UpdatedDatetime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[EventId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

# [dbo].[UserLoginTbl]

In [0]:
/****** Object:  Table [dbo].[UserLoginTbl]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserLoginTbl](
	[UserLoginTblId] [bigint] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](320) NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[ISActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UserLoginTblId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[UserTbl]

In [0]:
/****** Object:  Table [dbo].[UserTbl]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTbl](
	[UserTblId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NOT NULL,
	[Email] [varchar](320) NOT NULL,
	[Mobile] [varchar](10) NOT NULL,
	[Address] [varchar](200) NOT NULL,
	[CreatedTime] [datetime] NOT NULL,
	[Password] [varchar](100) NOT NULL,
	[UpdatedTime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[UserTblId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[ActivityTbl]

In [0]:
SET IDENTITY_INSERT [dbo].[ActivityTbl] ON 
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (1, N'matki fod ', N'in this we will play a matki fod game', 500, 10085, CAST(N'2024-04-24T15:05:00.000' AS DateTime), CAST(N'2024-04-25T15:05:00.000' AS DateTime), CAST(N'2024-04-24T15:05:41.320' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (2, N'singinfg hanuman chalisha ', N'in this we all together sing hanuman chalisha', 0, 10086, CAST(N'2024-05-16T15:07:00.000' AS DateTime), CAST(N'2024-05-18T15:07:00.000' AS DateTime), CAST(N'2024-04-24T15:07:36.317' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (4, N'uno playing', N'uno playing', 0, 10087, CAST(N'2024-04-30T15:09:00.000' AS DateTime), CAST(N'2024-04-30T15:09:00.000' AS DateTime), CAST(N'2024-04-24T15:09:17.523' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (6, N'try svg', N'dfdddddddddddddd', 0, 10094, CAST(N'2024-04-25T17:53:00.000' AS DateTime), CAST(N'2024-04-25T17:53:00.000' AS DateTime), CAST(N'2024-04-24T17:53:06.593' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (7, N'cccccccccccccccccc', N'cccccccccccccccccccccc', 500, 10095, CAST(N'2024-04-24T17:58:00.000' AS DateTime), CAST(N'2024-04-25T17:58:00.000' AS DateTime), CAST(N'2024-04-24T17:58:36.577' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (8, N'gggggggggggggggg', N'gggggggggggggggg', 100, 10096, CAST(N'2024-04-24T18:03:00.000' AS DateTime), CAST(N'2024-04-25T18:03:00.000' AS DateTime), CAST(N'2024-04-24T18:03:06.367' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (9, N'hhhhhhhhhhh', N'hhhhhhhhhhhhh', 500, 10097, CAST(N'2024-04-24T18:05:00.000' AS DateTime), CAST(N'2024-04-25T18:05:00.000' AS DateTime), CAST(N'2024-04-24T18:05:36.100' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10, N'bbbbbbbbbbbb', N'bbbbbbbbbbb', 500, 10097, CAST(N'2024-04-25T18:05:00.000' AS DateTime), CAST(N'2024-04-25T18:05:00.000' AS DateTime), CAST(N'2024-04-24T18:05:52.657' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (11, N'ssssaaaaaaaaaaaa', N'aaaaaaaaaaaa', 0, 10098, CAST(N'2024-04-25T18:06:00.000' AS DateTime), CAST(N'2024-04-25T18:06:00.000' AS DateTime), CAST(N'2024-04-24T18:06:35.400' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (12, N'sssssssssss', N'ssssssssssss', 500, 10099, CAST(N'2024-04-25T18:27:00.000' AS DateTime), CAST(N'2024-04-25T18:27:00.000' AS DateTime), CAST(N'2024-04-24T18:27:29.953' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (13, N'mmmmmmmmmmmmmmmmm', N'mmmmmmmmmm', 500, 10099, CAST(N'2024-04-25T18:27:00.000' AS DateTime), CAST(N'2024-04-25T18:27:00.000' AS DateTime), CAST(N'2024-04-24T18:27:45.843' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (14, N'iiiiiiiiiiiiiiiiii', N'iiiiiii', 500, 10099, CAST(N'2024-04-24T18:28:00.000' AS DateTime), CAST(N'2024-04-25T18:28:00.000' AS DateTime), CAST(N'2024-04-24T18:28:19.857' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10002, N'assd', N'sdsd', 0, 20085, CAST(N'2024-04-30T15:00:00.000' AS DateTime), CAST(N'2024-04-30T15:26:00.000' AS DateTime), CAST(N'2024-04-25T15:26:35.540' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10003, N'hjghj', N'hjghj', 0, 20086, CAST(N'2024-04-25T15:50:00.000' AS DateTime), CAST(N'2024-04-25T15:50:00.000' AS DateTime), CAST(N'2024-04-25T15:50:55.013' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10004, N'hjghj', N'hjbghj', 0, 20088, CAST(N'2024-04-26T15:00:00.000' AS DateTime), CAST(N'2024-04-26T15:51:00.000' AS DateTime), CAST(N'2024-04-25T15:51:09.623' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10005, N'sdasd', N'dasd', 0, 20089, CAST(N'2024-04-25T15:54:00.000' AS DateTime), CAST(N'2024-04-26T15:54:00.000' AS DateTime), CAST(N'2024-04-25T15:54:44.513' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10006, N'fsdf', N'fsdf', 0, 20089, CAST(N'2024-04-25T15:55:00.000' AS DateTime), CAST(N'2024-04-26T15:55:00.000' AS DateTime), CAST(N'2024-04-25T15:55:55.367' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10007, N'asdasd', N'asdasdas', 500, 20087, CAST(N'2024-04-25T16:00:00.000' AS DateTime), CAST(N'2024-04-25T16:19:00.000' AS DateTime), CAST(N'2024-04-25T16:19:17.857' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10008, N'Holica Dahan', N'this is holika dahan', 0, 20090, CAST(N'2024-09-26T17:38:00.000' AS DateTime), CAST(N'2024-09-27T17:38:00.000' AS DateTime), CAST(N'2024-04-25T17:38:24.240' AS DateTime), NULL)
INSERT [dbo].[ActivityTbl] ([ActivityId], [Name], [Description], [Price], [EventId], [StartDate], [EndDate], [CreatedDateTime], [UpdatedDateTime]) VALUES (10009, N'dfsdfsdf', N'fdfdf', 0, 20091, CAST(N'2024-04-25T18:00:00.000' AS DateTime), CAST(N'2024-04-25T18:07:00.000' AS DateTime), CAST(N'2024-04-25T18:07:56.693' AS DateTime), NULL)
SET IDENTITY_INSERT [dbo].[ActivityTbl] OFF
GO

# [dbo].[AdminTbl]

In [0]:
SET IDENTITY_INSERT [dbo].[AdminTbl] ON 
INSERT [dbo].[AdminTbl] ([AdminTblId], [Name], [Email], [Password], [Mobile], [Address], [UpdatedTime], [CreatedDatetime]) VALUES (1, N'Dalsukh', N'naneradalsukh@gmail.com', N'Dal@2002', N'7573942052', N'Dwarka', NULL, CAST(N'2024-04-03T15:58:27.607' AS DateTime))
SET IDENTITY_INSERT [dbo].[AdminTbl] OFF
GO

# [dbo].[EventTbl]

In [0]:
SET IDENTITY_INSERT [dbo].[EventTbl] ON 
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10085, N'janmastami', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-26T00:00:00.000' AS DateTime), N'this is festival of shree krishna ', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-05-04.jpg', 1, 1, CAST(N'2024-04-24T15:05:04.040' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10086, N'hanuman jayanti', CAST(N'2024-05-04T00:00:00.000' AS DateTime), CAST(N'2024-05-25T00:00:00.000' AS DateTime), N'festival of lord hanuman, birthday of lord hanuman', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-06-56.jpg', 1, 1, CAST(N'2024-04-24T15:06:31.590' AS DateTime), CAST(N'2024-04-24T15:06:56.213' AS DateTime))
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10087, N'fun friday', CAST(N'2024-04-30T00:00:00.000' AS DateTime), CAST(N'2024-04-30T00:00:00.000' AS DateTime), N'in this we will play different games', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-09-49.jpg', 1, 1, CAST(N'2024-04-24T15:08:12.260' AS DateTime), CAST(N'2024-04-24T15:09:49.970' AS DateTime))
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10088, N'sd', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'sdds', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-20-33.jpg', 0, 0, CAST(N'2024-04-24T15:20:33.113' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10089, N'sdddddddd', CAST(N'2024-04-25T00:00:00.000' AS DateTime), CAST(N'2024-04-26T00:00:00.000' AS DateTime), N'ddddddd', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-20-51.jpg', 0, 0, CAST(N'2024-04-24T15:20:51.083' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10090, N'ddfffffffffffffffffffff', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'ffffffffffffffffffffff', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\16-01-45.jpg', 0, 0, CAST(N'2024-04-24T16:01:46.007' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10091, N'sssssssssssssssssssssssssssss', CAST(N'2024-04-25T00:00:00.000' AS DateTime), CAST(N'2024-04-26T00:00:00.000' AS DateTime), N'ssssssssssssssssssssssssssssssss', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\16-03-22.jpg', 0, 0, CAST(N'2024-04-24T16:03:22.740' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10093, N'gtgtgtgtgtgtgtgtgtgtgtgt', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'ttttttttttttttttttt', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\17-48-56.jpg', 0, 0, CAST(N'2024-04-24T17:48:56.240' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10094, N'fffffffffffffffffffff', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'ffffffffffffffffffffffffffff', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\17-50-47.jpg', 1, 1, CAST(N'2024-04-24T17:50:47.860' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10095, N'ddddddddddddd', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'dddddddddddd', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\17-56-23.jpg', 1, 1, CAST(N'2024-04-24T17:56:23.110' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10096, N'zzzzzzzzzzzzzzzzz', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'zzzzzzzzzzzz', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\18-02-15.jpg', 1, 1, CAST(N'2024-04-24T18:02:15.923' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10097, N'fff', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'fffff', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\18-05-26.jpg', 1, 1, CAST(N'2024-04-24T18:05:26.333' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10098, N'sssssssssss', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'sssssssssss', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\18-06-26.jpg', 1, 1, CAST(N'2024-04-24T18:06:26.437' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (10099, N'aaaaaaaaaaa', CAST(N'2024-04-24T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'aaaaaaaaaaaaaaa', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\18-27-08.jpg', 1, 1, CAST(N'2024-04-24T18:27:08.273' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20085, N'asasas', CAST(N'2024-04-30T00:00:00.000' AS DateTime), CAST(N'2024-04-30T00:00:00.000' AS DateTime), N'asass', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-26-27.jpg', 1, 1, CAST(N'2024-04-25T15:26:27.550' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20086, N'sdasjas', CAST(N'2024-01-12T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'asddsdf', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-45-41.jpg', 1, 1, CAST(N'2024-04-25T15:45:41.110' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20087, N'edsef', CAST(N'2024-04-25T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'fsdf', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-47-41.jpg', 1, 1, CAST(N'2024-04-25T15:47:41.237' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20088, N'sdasdasd', CAST(N'2024-04-26T00:00:00.000' AS DateTime), CAST(N'2024-04-26T00:00:00.000' AS DateTime), N'asdasdd', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-49-31.jpg', 1, 1, CAST(N'2024-04-25T15:49:31.823' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20089, N'wqw', CAST(N'2024-04-25T00:00:00.000' AS DateTime), CAST(N'2024-04-26T00:00:00.000' AS DateTime), N'asdas', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\15-54-34.jpg', 0, 1, CAST(N'2024-04-25T15:54:34.100' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20090, N'Holi', CAST(N'2024-09-25T00:00:00.000' AS DateTime), CAST(N'2024-09-28T00:00:00.000' AS DateTime), N'Holi dahan', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\17-38-02.jpg', 1, 1, CAST(N'2024-04-25T17:38:02.800' AS DateTime), NULL)
INSERT [dbo].[EventTbl] ([EventId], [Name], [StartDate], [EndDate], [Description], [Image], [IsActive], [IsPublish], [CreadDateTime], [UpdatedDatetime]) VALUES (20091, N'testing', CAST(N'2024-04-25T00:00:00.000' AS DateTime), CAST(N'2024-04-25T00:00:00.000' AS DateTime), N'fdfdfdsf', N'C:\Users\dalsu\OneDrive\Desktop\Intern\EventModule\EventModule\Images\18-07-22.jpg', 1, 1, CAST(N'2024-04-25T18:07:22.537' AS DateTime), NULL)
SET IDENTITY_INSERT [dbo].[EventTbl] OFF
GO

# [dbo].[UserTbl]

In [0]:
SET IDENTITY_INSERT [dbo].[UserTbl] ON 
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (7, N'Nanera Dalsukh', N'naneradalsukh@gmail.com', N'7573942025', N'Dwarka', CAST(N'2024-04-03T15:58:27.607' AS DateTime), N'Dal@2002', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (8, N'virat kohli', N'virat@gmail.com', N'7573942025', N'jamnagar', CAST(N'2024-04-03T16:01:47.510' AS DateTime), N'Vir@2002', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (9, N'Robert', N'robert@gmail.com', N'4566544565', N'Jamnagar', CAST(N'2024-04-04T17:07:39.900' AS DateTime), N'dfgfgfg', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (10, N'Robert', N'thisiscoder@gmail.com', N'1236457898', N'dsadigugtggggggggggggg', CAST(N'2024-04-10T13:42:04.217' AS DateTime), N'iggh', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (11, N'demo', N'demo@gmail.com', N'4566544565', N'sassasdasdasdddddddddddd', CAST(N'2024-04-10T13:43:36.753' AS DateTime), N'dfvf', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (12, N'sdcbcx', N'dd@gmail.com', N'4566544565', N'wwedffdfdf', CAST(N'2024-04-10T13:45:27.733' AS DateTime), N'ghgfhhh', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (13, N'bgnhgh', N'ok@gmail.com', N'4566544565', N'weawear', CAST(N'2024-04-10T13:56:43.370' AS DateTime), N'sdzdfdf', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (14, N'new joine', N'joine@gmail.com', N'4566544565', N'dsdff', CAST(N'2024-04-16T11:51:42.397' AS DateTime), N'Joine@gmail.com', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (15, N'anurag', N'100', N'3', N'AddPrice', CAST(N'2024-04-17T18:05:40.600' AS DateTime), N'2123', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (16, N'Nanera Dalsukh', N'neneradalsukh@gmail.com', N'4566544565', N'Jamnagar', CAST(N'2024-04-22T11:11:32.710' AS DateTime), N'asass', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (18, N'anurag', N'pupose@gmail.com', N'3222222222', N'AddPrice', CAST(N'2024-04-25T11:45:16.570' AS DateTime), N'2123', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (20, N'dfdddddddddd', N'd@gmail.com', N'4566544565', N'ddddddddddd', CAST(N'2024-04-25T11:54:49.843' AS DateTime), N'Dal@2002', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (21, N'asasasd', N'b@gmail.com', N'4566544565', N'dfdfd', CAST(N'2024-04-25T12:02:42.660' AS DateTime), N'Dal@2002', NULL)
INSERT [dbo].[UserTbl] ([UserTblId], [Name], [Email], [Mobile], [Address], [CreatedTime], [Password], [UpdatedTime]) VALUES (22, N'Amit', N'amit@gmail.com', N'4566544565', N'surat', CAST(N'2024-04-25T12:26:41.090' AS DateTime), N'Dal@2002', NULL)
SET IDENTITY_INSERT [dbo].[UserTbl] OFF
GO

# [UQ__AdminTbl__A9D105343322D447]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__AdminTbl__A9D105343322D447]    Script Date: 25-04-2024 18:39:18 ******/
ALTER TABLE [dbo].[AdminTbl] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [UQ__EventTbl__737584F638D433B0]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__EventTbl__737584F638D433B0]    Script Date: 25-04-2024 18:39:18 ******/
ALTER TABLE [dbo].[EventTbl] ADD UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [UQ__UserLogi__A9D10534AD5EA8DE]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__UserLogi__A9D10534AD5EA8DE]    Script Date: 25-04-2024 18:39:18 ******/
ALTER TABLE [dbo].[UserLoginTbl] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [UQ__UserTbl__A9D10534B907F20D]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__UserTbl__A9D10534B907F20D]    Script Date: 25-04-2024 18:39:18 ******/
ALTER TABLE [dbo].[UserTbl] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [FK__ActivityT__Event__4E88ABD4]

In [0]:
ALTER TABLE [dbo].[ActivityTbl]  WITH CHECK ADD FOREIGN KEY([EventId])
REFERENCES [dbo].[EventTbl] ([EventId])
GO

# [dbo].[Add_Activity_SP]

In [0]:
/****** Object:  StoredProcedure [dbo].[Add_Activity_SP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for Adding an activity>
-- =============================================
CREATE proc [dbo].[Add_Activity_SP] --'uno','playing uno',1,'2024-04-03 15:58:27.607','2024-04-04 15:58:27.607'
@Name varchar(100),
@Description  varchar(100),
@EventId bigint,
@StartDate datetime,
@EndDate datetime

as 
begin
declare @Id bigint ;
--first check that activity is already exists or not 
select @Id = ActivityId from ActivityTbl where Name = @Name AND EventId = @EventId ;

if @Id IS NOT NULL
begin
select 'Already Exists Activity' as ResponseMessage, 0 as ID 
return
end

--checking that there is any events or not 
declare @cnt bigint ;
select @cnt = COUNT(EventId) from EventTbl ;

if @cnt = 0
begin
select 'there is no events' as ResponseMessage, 0 as ID
return end 

insert into ActivityTbl values(@Name,@Description,0,@EventId,@StartDate,@EndDate,GETDATE(),null);
select 'Addedd successfully' as ResponseMessage, 1 as ID 
end 

GO

# [dbo].[Add_Event_SP]

In [0]:
/****** Object:  StoredProcedure [dbo].[Add_Event_SP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for Adding an Event>
-- =============================================
CREATE proc [dbo].[Add_Event_SP]
@Name varchar(100),
@Description varchar(MAX),
@StartDate datetime,
@Enddate datetime,
@Image varchar(MAX)

as
begin



declare @Id bigint ;
select @Id	= EventId from EventTbl where Name = @Name ;
--first check that Event is already exists or not 
if @Id IS NOT NULL
begin
select 'Already Exist' as ResponseMessage, 0 as ID
return
end 

insert into EventTbl values(@Name,@StartDate,@Enddate,@Description,@Image,1,0,GETDATE(),null);
select 'Addedd successfully' as ResponseMessage, 1 as ID 
end 





GO

# [dbo].[LoginSP]

In [0]:
/****** Object:  StoredProcedure [dbo].[LoginSP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for Login user or Admin>
-- =============================================
CREATE proc  [dbo].[LoginSP] 
@Email varchar(320),
@Password varchar(100),
@Flag varchar(100)
as
begin 
--checking that flag is provided or not 
if @Flag IS null
begin
select 'Please Provide flag' as ResponseMessage, 0 as ID 
return 
end 

declare  @Id bigint ; 
--for user login check email and password 
if @Flag = 'UserLogin'
begin
select @Id = UserTBLId from UserTbl where Email = @Email AND Password = @Password ;  

if @Id is null
begin
select 'provided credetails is wrong' as ResponseMessage , 0 as ID 
return
end
select 'Login successfully' as ResponseMessage, 1 as ID
end

--for Admin login check email and password
if @Flag = 'AdminLogin'
begin
select @Id = AdminTblId from AdminTbl where Email = @Email AND Password = @Password ;  
if @Id is null
begin
select 'provided credetails is wrong' as ResponseMessage , 0 as ID 
return
end
--and if Email and Password is right so sending Login successfully
select 'Login successfully' as ResponseMessage, 1 as ID
end

end 

GO

# [dbo].[MonthwiseSP]

In [0]:
/****** Object:  StoredProcedure [dbo].[MonthwiseSP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[MonthwiseSP]
@Month bigint

as 
begin

declare @count bigint ;
select @count = COUNT(EventId) from EventTbl where  MONTH(StartDate) = @Month AND IsActive = 1;
if @count = 0
begin
select 'DO not have any Events' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select EventId,Name,StartDate,EndDate,Description,Image,IsPublish from EventTbl  where  MONTH(StartDate) = @Month AND IsActive = 1 AND IsPublish = 1 
end

select * from EventTbl;
GO

# [dbo].[Publish_AddPrice_SP]

In [0]:
/****** Object:  StoredProcedure [dbo].[Publish_AddPrice_SP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for Adding Price,publish or Delete>
-- =============================================
CREATE proc [dbo].[Publish_AddPrice_SP]
@Price bigint,
@ActivityId bigint,
@EventId bigint,
@Flag varchar(100)
as
begin

if @Flag = 'Publish'
begin

declare @count bigint ;
select @count = COUNT(ActivityId) from ActivityTbl where EventId = @EventId ;

if @count = 0
begin 
select 'You can not publish this becuase you have to first add atleast one activity' as ResponseMessage, 0 as ID
return 
end

update EventTbl set IsPublish =1 where EventId = @EventId ;
select 'Publish successfully' as ResponseMessage, 1 as ID
end 

if @Flag = 'AddPrice'
begin
update ActivityTbl set Price = @Price where ActivityId = @ActivityId ;
select 'Updated Successfully' as ResponseMessage, 1 as ID 
end

if @Flag = 'DeleteEvent'
begin

declare @EventDeleteId bigint ;
select @EventDeleteId = EventId from EventTbl where EventId = @EventId ;

if @EventDeleteId IS NULL
begin
select 'please provide valid EventId' as ResponseMessage, 0 as ID 
return 
end

update EventTbl set IsActive = 0 where EventId = @EventId ;
select 'Deleted Successfully' as ResponseMessage, 1 as ID 
end

if @Flag = 'UnPublish'
begin
update EventTbl set IsPublish =0 where EventId = @EventId ;
select 'UnPublish successfully' as ResponseMessage, 1 as ID
end
end 
GO

# [dbo].[RegisterUser_SP]

In [0]:
/****** Object:  StoredProcedure [dbo].[RegisterUser_SP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for Register User>
-- =============================================

CREATE proc  [dbo].[RegisterUser_SP]  --'Dalsukh','naneradalsukh@gmail.com','4566544568','Dwarka','Dal@2002'
@Name varchar(100),
@Email varchar(320),
@Mobile varchar(10),
@Address varchar(100),
@Password varchar(100)
as
begin 
declare @Id bigint ;
select @Id = UserTblId from UserTbl where Email = @Email ;

--first check if user is already registered or not 
if @Id IS NOT NULL
begin 
select 'User is already Registered' as Resultmessage, 0 as ID
return
end 

insert into UserTbl values(@Name,@Email,@Mobile,@Address,GETDATE(),@Password,null) ;
select 'Register Successfully' as Resultmessage,1 as ID;
select UserTblId,Name,Email,Mobile,Address,CreatedTime,Password from UserTbl where Email = @Email ;
end
GO

# [dbo].[Showing_Event_Activity_SP]

In [0]:
/****** Object:  StoredProcedure [dbo].[Showing_Event_Activity_SP]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		<Author,,Nanera Dalsukh>
-- Create date: <04-04-2024>
-- Description:	<for showing an Event or Activity>
-- =============================================
CREATE proc [dbo].[Showing_Event_Activity_SP] --1,'ActibityShow'
@EventId bigint,
@Flag varchar(1000)

as 
begin 

declare @count bigint ;

if @Flag IS NULL
begin
select 'please provide valid flag' as ResponseMessage, 0 as ID 
return
end

--showing only non published Events 
if @Flag = 'AdminEvents'
begin
select @count = COUNT(EventId) from EventTbl where IsPublish = 0 AND EndDate >=CONVERT(date, GETDATE()) AND IsActive = 1
if @count = 0
begin
select 'Do not have any Event To publish' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select [EventId],[Name],[StartDate],[EndDate],[Description],[Image] from EventTbl where IsPublish = 0 AND EndDate >=CONVERT(date, GETDATE()) AND IsActive = 1
end

--showing only published Events 
if @Flag = 'EmployeeEvent'

begin
select @count = COUNT(EventId) from EventTbl where IsPublish = 1 AND EndDate >=CONVERT(date, GETDATE()) AND IsActive = 1;
if @count = 0
begin
select 'DO not have any scheduled by Admin' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select EventId, Name,StartDate,EndDate,Description,Image from EventTbl  where IsPublish = 1 AND  EndDate >=CONVERT(date, GETDATE())
AND IsActive = 1
end

--showing all the Activities 
if @Flag = 'ActibityShow'
begin


select @count = COUNT(ActivityId) from ActivityTbl where EventId = @EventId ;
if @count = 0
begin
select 'Do not have any activity yet' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select Name,Description,Price,EventId,StartDate,EndDate from ActivityTbl where EventId = @EventId ;
end 

--showing only Activities which don't have price
if @Flag = 'AdminActibityShow'
begin


select @count = COUNT(ActivityId) from ActivityTbl where EventId = @EventId AND Price = 0 ;
if @count = 0
begin
select 'Do not have any activity to add price' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select ActivityId,Name,Description,Price,EventId,StartDate,EndDate from ActivityTbl where EventId = @EventId AND Price = 0;
end 

--showing only on going Events 
if @Flag = 'Ongoing-Events'
begin


select @count = COUNT(EventId) from EventTbl where IsPublish = 1 AND (CONVERT(date, GETDATE()) between StartDate AND EndDate) AND IsActive = 1;
if @count = 0
begin
select 'DO not have any scheduled by Admin' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select EventId,Name,StartDate,EndDate,Description,Image from EventTbl  where IsPublish = 1 AND (CONVERT(date, GETDATE()) between StartDate AND EndDate) AND IsActive = 1;

end

--showing only upcoming Events 
if @Flag = 'Upcoming-Events'
begin


select @count = COUNT(EventId) from EventTbl where IsPublish = 1 AND StartDate>CONVERT(date, GETDATE()) AND IsActive = 1;
if @count = 0
begin
select 'DO not have any scheduled by Admin' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select EventId,Name,StartDate,EndDate,Description,Image from EventTbl  where IsPublish = 1 AND StartDate >CONVERT(date, GETDATE()) AND IsActive = 1;

end

--showing all the Events 
if @Flag = 'AllEvent'

begin
select @count = COUNT(EventId) from EventTbl where   EndDate >=CONVERT(date, GETDATE()) AND IsActive = 1;
if @count = 0
begin
select 'DO not have any Events' as ResponseMessage, 0 as ID
return 
end

select 'Fetched Successfully' as ResponseMessage, 1 as ID 
select EventId,Name,StartDate,EndDate,Description,Image,IsPublish from EventTbl  where  EndDate >=CONVERT(date, GETDATE()) AND IsActive = 1
end


end 

GO

# [dbo].[SPUpdateEvent]

In [0]:
/****** Object:  StoredProcedure [dbo].[SPUpdateEvent]    Script Date: 25-04-2024 18:39:18 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[SPUpdateEvent]
@Name varchar(100),
@Description varchar(MAX),
@StartDate datetime,
@EndDate datetime,
@Image varchar(MAX),
@EventId bigint 

as begin


declare @Id bigint ;
select @Id = EventId from EventTbl where EventId = @EventId 

--first check EventId is valid or not 
if @EventId IS NULL
begin
select 'not valid Event' as ResponseMessage, 0 as ID
return
end
--if EventId is valid so update the Event 
update EventTbl set Name = @Name, Description = @Description, StartDate = @StartDate, EndDate = @EndDate, Image = @Image,UpdatedDatetime = GETDATE() where EventId = @EventId;
delete from ActivityTbl where (CONVERT(date, StartDate) < CONVERT(date, @StartDate) OR CONVERT(date, EndDate) > CONVERT(date, @EndDate)) AND EventId = @EventId;
select 'Updated successfully' as ResponseMessage, 1 as ID
end

select * from EventTbl;
GO

# [EventModule]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [EventModule] SET  READ_WRITE 
GO