# [Library]

In [0]:
USE [master]
GO

In [0]:
/****** Object:  Database [Library]    Script Date: 09-04-2024 16:40:41 ******/
CREATE DATABASE [Library]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Library', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Library.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Library_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\Library_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [Library] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Library].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Library] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Library] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Library] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Library] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Library] SET ARITHABORT OFF 
GO
ALTER DATABASE [Library] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Library] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Library] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Library] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Library] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Library] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Library] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Library] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Library] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Library] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Library] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Library] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Library] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Library] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Library] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Library] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Library] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Library] SET RECOVERY FULL 
GO
ALTER DATABASE [Library] SET  MULTI_USER 
GO
ALTER DATABASE [Library] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Library] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Library] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Library] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Library] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [Library] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'Library', N'ON'
GO
ALTER DATABASE [Library] SET QUERY_STORE = ON
GO
ALTER DATABASE [Library] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

# [dbo].[Admin]

In [0]:
USE [Library]
GO

In [0]:
/****** Object:  Table [dbo].[Admin]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
	[Name] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Book]

In [0]:
/****** Object:  Table [dbo].[Book]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Book](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [varchar](50) NULL,
	[Author] [varchar](50) NULL,
	[BookCount] [int] NULL,
	[Category] [int] NULL,
	[AvailableBook] [int] NULL,
	[BookOwn] [int] NULL,
	[CreatedDate] [datetime] NULL,
	[UpdatedDate] [datetime] NULL,
	[CreatedBy] [int] NULL,
	[UpdatedBy] [int] NULL,
	[Edition] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[BookBorrowHistory]

In [0]:
/****** Object:  Table [dbo].[BookBorrowHistory]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookBorrowHistory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BookId] [int] NULL,
	[BorrowBy] [int] NULL,
	[BorrowTime] [datetime] NULL,
	[ReturnTime] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[BookCategory]

In [0]:
/****** Object:  Table [dbo].[BookCategory]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BookCategory](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[CategoryName] [varchar](35) NULL,
	[CreatedTime] [datetime] NULL,
	[CreatedBy] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Expenses]

In [0]:
/****** Object:  Table [dbo].[Expenses]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Expenses](
	[ExpenseId] [bigint] IDENTITY(1,1) NOT NULL,
	[Comment] [varchar](100) NULL,
	[CreditOrDebit] [varchar](10) NULL,
	[Amount] [bigint] NULL,
	[ExpenseTime] [datetime] NULL,
	[balance] [bigint] NULL,
	[UserId] [bigint] NULL,
PRIMARY KEY CLUSTERED 
(
	[ExpenseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Users]

In [0]:
/****** Object:  Table [dbo].[Users]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[UsersId] [bigint] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](100) NULL,
	[Email] [varchar](320) NULL,
	[Mobile] [varchar](10) NULL,
	[Address] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[UsersId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[UserTable]

In [0]:
/****** Object:  Table [dbo].[UserTable]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserTable](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Email] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
	[CreatedDatetime] [datetime] NULL,
	[Name] [varchar](200) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Admin]

In [0]:
SET IDENTITY_INSERT [dbo].[Admin] ON 
INSERT [dbo].[Admin] ([Id], [Email], [Password], [Name]) VALUES (4, N'naneradalsukh@gmail.com', N'Dal@2002', N'Dalsukh')
INSERT [dbo].[Admin] ([Id], [Email], [Password], [Name]) VALUES (5, N'sanjaymakvana@gmail.com', N'San@2002', N'Sanjay')
INSERT [dbo].[Admin] ([Id], [Email], [Password], [Name]) VALUES (1005, N'amit@gmail.com', N'Amit@2002', N'Amit')
SET IDENTITY_INSERT [dbo].[Admin] OFF
GO

# [dbo].[Book]

In [0]:
SET IDENTITY_INSERT [dbo].[Book] ON 
INSERT [dbo].[Book] ([Id], [Title], [Author], [BookCount], [Category], [AvailableBook], [BookOwn], [CreatedDate], [UpdatedDate], [CreatedBy], [UpdatedBy], [Edition]) VALUES (3, N'spiderman', N'aadarsh', 5, 8, 2, 1, CAST(N'2024-02-28T18:26:03.090' AS DateTime), CAST(N'2024-03-07T17:17:35.833' AS DateTime), 4, 4, N'3')
INSERT [dbo].[Book] ([Id], [Title], [Author], [BookCount], [Category], [AvailableBook], [BookOwn], [CreatedDate], [UpdatedDate], [CreatedBy], [UpdatedBy], [Edition]) VALUES (4, N'Dr.Strange', N'Amit', 5, 8, 4, 2, CAST(N'2024-02-29T11:24:27.620' AS DateTime), CAST(N'2024-02-29T11:45:35.677' AS DateTime), 1005, 4, N'2')
INSERT [dbo].[Book] ([Id], [Title], [Author], [BookCount], [Category], [AvailableBook], [BookOwn], [CreatedDate], [UpdatedDate], [CreatedBy], [UpdatedBy], [Edition]) VALUES (6, N'thor''', N'dalsukh', 5, 8, 5, NULL, CAST(N'2024-03-13T15:17:25.540' AS DateTime), NULL, 4, NULL, N'1.2')
SET IDENTITY_INSERT [dbo].[Book] OFF
GO

# [dbo].[BookBorrowHistory]

In [0]:
SET IDENTITY_INSERT [dbo].[BookBorrowHistory] ON 
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (1, 3, 1, CAST(N'2024-02-28T18:54:22.390' AS DateTime), CAST(N'2024-02-28T19:09:50.120' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (2, 3, 1, CAST(N'2024-02-29T11:11:22.783' AS DateTime), CAST(N'2024-02-29T11:34:52.547' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (3, 3, 2, CAST(N'2024-02-29T11:17:34.823' AS DateTime), CAST(N'2024-02-29T11:33:09.297' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (4, 3, 1, CAST(N'2024-02-29T11:41:38.773' AS DateTime), CAST(N'2024-02-29T11:43:37.383' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (5, 3, 2, CAST(N'2024-02-29T11:42:08.027' AS DateTime), CAST(N'2024-02-29T11:42:39.927' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (7, 3, 1, CAST(N'2024-02-29T12:39:54.740' AS DateTime), CAST(N'2024-02-29T12:43:01.570' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (8, 4, 1, CAST(N'2024-02-29T12:42:19.643' AS DateTime), CAST(N'2024-03-15T18:01:03.843' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (9, 3, 2, CAST(N'2024-02-29T12:43:36.917' AS DateTime), NULL)
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (10, 3, 3, CAST(N'2024-02-29T12:58:26.637' AS DateTime), NULL)
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (11, 3, 1, CAST(N'2024-03-15T17:57:55.867' AS DateTime), CAST(N'2024-03-15T17:58:39.390' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (12, 3, 1, CAST(N'2024-03-15T18:00:36.617' AS DateTime), NULL)
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (13, 4, 1, CAST(N'2024-03-15T18:08:40.063' AS DateTime), CAST(N'2024-03-15T18:09:47.847' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (14, 4, 1, CAST(N'2024-03-15T18:10:00.480' AS DateTime), CAST(N'2024-03-15T18:10:11.850' AS DateTime))
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (15, 4, 1, CAST(N'2024-03-15T18:10:16.480' AS DateTime), NULL)
INSERT [dbo].[BookBorrowHistory] ([Id], [BookId], [BorrowBy], [BorrowTime], [ReturnTime]) VALUES (16, 4, 2, CAST(N'2024-03-15T18:11:26.020' AS DateTime), CAST(N'2024-03-15T18:12:40.110' AS DateTime))
SET IDENTITY_INSERT [dbo].[BookBorrowHistory] OFF
GO

# [dbo].[BookCategory]

In [0]:
SET IDENTITY_INSERT [dbo].[BookCategory] ON 
INSERT [dbo].[BookCategory] ([Id], [CategoryName], [CreatedTime], [CreatedBy]) VALUES (8, N'marvel', CAST(N'2024-02-28T18:16:31.640' AS DateTime), 4)
INSERT [dbo].[BookCategory] ([Id], [CategoryName], [CreatedTime], [CreatedBy]) VALUES (1005, N'Education', CAST(N'2024-02-29T11:44:08.903' AS DateTime), 4)
INSERT [dbo].[BookCategory] ([Id], [CategoryName], [CreatedTime], [CreatedBy]) VALUES (1006, N'politics', CAST(N'2024-03-13T15:38:32.550' AS DateTime), 4)
INSERT [dbo].[BookCategory] ([Id], [CategoryName], [CreatedTime], [CreatedBy]) VALUES (1007, N'fun', CAST(N'2024-03-15T17:53:38.097' AS DateTime), 4)
SET IDENTITY_INSERT [dbo].[BookCategory] OFF
GO

# [dbo].[UserTable]

In [0]:
SET IDENTITY_INSERT [dbo].[UserTable] ON 
INSERT [dbo].[UserTable] ([Id], [Email], [Password], [CreatedDatetime], [Name]) VALUES (1, N'savansolanki@gmail.com', N'Sav@2002', CAST(N'2024-02-28T18:32:31.907' AS DateTime), N'savan')
INSERT [dbo].[UserTable] ([Id], [Email], [Password], [CreatedDatetime], [Name]) VALUES (2, N'satishnanera@gmail.com', N'Sat@2002', CAST(N'2024-02-29T11:14:12.717' AS DateTime), N'satish')
INSERT [dbo].[UserTable] ([Id], [Email], [Password], [CreatedDatetime], [Name]) VALUES (3, N'darshan@gmail.com', N'Dar@2002', CAST(N'2024-02-29T12:57:48.903' AS DateTime), N'Darshan')
SET IDENTITY_INSERT [dbo].[UserTable] OFF
GO

# [UQ__Users__A9D10534D20550E2]

In [0]:
SET ANSI_PADDING ON
GO
/****** Object:  Index [UQ__Users__A9D10534D20550E2]    Script Date: 09-04-2024 16:40:41 ******/
ALTER TABLE [dbo].[Users] ADD UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

# [FK__Book__BookOwn__403A8C7D]

In [0]:
ALTER TABLE [dbo].[Book]  WITH CHECK ADD FOREIGN KEY([BookOwn])
REFERENCES [dbo].[UserTable] ([Id])
GO

# [FK__Book__Category__3F466844]

In [0]:
ALTER TABLE [dbo].[Book]  WITH CHECK ADD FOREIGN KEY([Category])
REFERENCES [dbo].[BookCategory] ([Id])
GO

# [FK__Book__CreatedBy__3D5E1FD2]

In [0]:
ALTER TABLE [dbo].[Book]  WITH CHECK ADD FOREIGN KEY([CreatedBy])
REFERENCES [dbo].[Admin] ([Id])
GO

# [FK__Book__UpdatedBy__3E52440B]

In [0]:
ALTER TABLE [dbo].[Book]  WITH CHECK ADD FOREIGN KEY([UpdatedBy])
REFERENCES [dbo].[Admin] ([Id])
GO

# [FK__BookBorro__BookI__4AB81AF0]

In [0]:
ALTER TABLE [dbo].[BookBorrowHistory]  WITH CHECK ADD FOREIGN KEY([BookId])
REFERENCES [dbo].[Book] ([Id])
GO

# [FK__BookBorro__Borro__4BAC3F29]

In [0]:
ALTER TABLE [dbo].[BookBorrowHistory]  WITH CHECK ADD FOREIGN KEY([BorrowBy])
REFERENCES [dbo].[UserTable] ([Id])
GO

# [FK__BookCateg__Creat__46E78A0C]

In [0]:
ALTER TABLE [dbo].[BookCategory]  WITH CHECK ADD FOREIGN KEY([CreatedBy])
REFERENCES [dbo].[Admin] ([Id])
GO

# [FK__Expenses__UserId__797309D9]

In [0]:
ALTER TABLE [dbo].[Expenses]  WITH CHECK ADD FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([UsersId])
GO

# [dbo].[BookOwnShow]

In [0]:
/****** Object:  StoredProcedure [dbo].[BookOwnShow]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[BookOwnShow]
as
begin try
select Book.Id , Book.Edition,Book.Title, BookBorrowHistory.BorrowBy, UserTable.Name from Book inner join BookBorrowHistory on Book.Id = BookBorrowHistory.BookId inner join UserTable on BookBorrowHistory.BorrowBy = UserTable.Id where BookBorrowHistory.ReturnTime is null ;
end try
begin catch
print ERROR_MESSAGE();
end catch;
GO

# [dbo].[BookSelectOrDelete]

In [0]:
/****** Object:  StoredProcedure [dbo].[BookSelectOrDelete]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[BookSelectOrDelete]
@BookId int,
@OperationType varchar(80)
as
begin try

if(@OperationType = 'SeeBooks')
begin
select Id,Title,Author,Edition from Book ;
end;

if(@OperationType = 'Delete')
begin
delete from BookBorrowHistory where BookId = @BookId ;
delete from Book where Id = @BookId ;
end;



end try 

begin catch
print ERROR_MESSAGE()
end catch ;
GO

# [dbo].[BorrowHistoryEntry]

In [0]:
/****** Object:  StoredProcedure [dbo].[BorrowHistoryEntry]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[BorrowHistoryEntry]
@UserId int,
@BookId int, 
@OperationType varchar(40)
as 
 begin try
 if(@OperationType = 'BookTableEntry')
 begin
 UPDATE Book set BookOwn = @UserId,AvailableBook=AvailableBook-1 where Id = @BookId;
 end;

 if(@OperationType = 'BorrowHistory')
 begin
 insert into BookBorrowHistory(Bookid,BorrowBy,borrowTime) values(@BookId,@UserId,GETDATE());
 end;

 if(@OperationType = 'ReturnEntryInBook')
 begin
 UPDATE Book set AvailableBook = AvailableBook+1 where Id = @BookId
 end;

  if(@OperationType = 'ReturnEntryInBookHistory')
 begin
 update BookBorrowHistory set ReturnTime = GETDATE() where Bookid = @BookId AND BorrowBy = @UserId AND ReturnTime IS NULL
 end;

 end try

 begin catch
 select 'there is some issue';
 end catch;
GO

# [dbo].[CategoryFind]

In [0]:
/****** Object:  StoredProcedure [dbo].[CategoryFind]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[CategoryFind]
@CategoryName varchar(50),
@result int OUT,
@Count int OUT
as
begin try

select @result = Id from BookCategory where CategoryName = @CategoryName ;
select @Count = COUNT(*) from BookCategory where CategoryName = @CategoryName ;


end try
begin catch
select 'there is some issue';
end catch ;
GO

# [dbo].[InsertCategory]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertCategory]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[InsertCategory]
@CategoryName varchar(50),
@CreatedBy int
as
begin try

insert into BookCategory(CategoryName,CreatedBy,CreatedTime) values(@CategoryName,@CreatedBy,GETDATE());

end try 

begin catch
select 'there is some issue' as message 
end catch;
GO

# [dbo].[InsertIntoBook]

In [0]:
/****** Object:  StoredProcedure [dbo].[InsertIntoBook]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

create proc [dbo].[InsertIntoBook]
@BookId int,
@OperationType varchar(80),
@Title varchar(50),
@Author varchar(50),
@Category int,
@CreatedBy int,
@UpdatedBy int,
@BookCount int,
@AvailableBook int,
@Edition float,
@BookOwn int
as
begin try


if(@OperationType = 'InsertBook')
begin
insert into Book(Title,Author,Category,CreatedDate,CreatedBy,BookCount,Edition,AvailableBook) values(@Title, @Author, @Category,GETDATE(),@CreatedBy,@BookCount, @Edition, @AvailableBook);
end;



if(@OperationType = 'UpdateBook')
begin
UPDATE Book set Title = @Title, Author = @Author, Category=@Category,UpdatedDate = GETDATE(),UpdatedBy = @UpdatedBy, Edition = @Edition where Id = @BookId ;
end;

end try

begin catch
select 'there is some issue' as message
end catch
GO

# [dbo].[IsAvailable]

In [0]:
/****** Object:  StoredProcedure [dbo].[IsAvailable]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[IsAvailable]
@Email varchar(30),
@Password varchar(200), 
@OperationType varchar(40),
@Name varchar(200),
@Result int out,
@Count int OUT 
as 
 begin try
 if(@OperationType = 'UserRegister')
 begin
insert into UserTable values(@Email,@Password,GETDATE(),@Name);
 end;

 if(@OperationType = 'UserExistence')
 begin
select @Result = Id from UserTable where Email = @Email AND Password = @Password ;
select @Count = COUNT(*) from UserTable where Email = @Email AND Password = @Password ;
 end;

 if(@OperationType = 'AdminExist')
 begin
select @Result = Id  from Admin where Email = @Email AND Password = @Password ;
select @Count = COUNT(*)  from Admin where Email = @Email AND Password = @Password ;
 end;

 end try

 begin catch
 select 'there is some issue';
 end catch;
GO

# [dbo].[UserBooks]

In [0]:
/****** Object:  StoredProcedure [dbo].[UserBooks]    Script Date: 09-04-2024 16:40:41 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE proc [dbo].[UserBooks]
@UserId int,
@OperationType varchar(50)
as 
begin try

if(@OperationType = 'UserBooks')
begin
select BookBorrowHistory.Bookid, Book.title, Book.Edition from BookBorrowHistory inner join Book on BookBorrowHistory.Bookid = Book.Id where BookBorrowHistory.BorrowBy = @UserId AND BookBorrowHistory.ReturnTime IS NULL;
end;

if(@OperationType = 'AvailableForUser')
begin
select Id,Title,Edition from Book where AvailableBook > 0 AND Book.ID NOT IN (select Bookid from BookBorrowHistory where BorrowBy = @UserId AND BookBorrowHistory.ReturnTime IS NULL);
end;

end try
begin catch
select 'there is an issue'
end catch ;
GO

# [Library]

In [0]:
USE [master]
GO

In [0]:
ALTER DATABASE [Library] SET  READ_WRITE 
GO